// Package script renders the human-readable script for a locale from the
// project itself.
//
// It exists because narration had two homes. A script written as prose in a doc
// and then re-typed into content/<locale>.yaml is two files that agree only
// until the first edit — and the edit always comes, because a line written to be
// read is not yet a line written to be spoken. The session this came from paid
// for that twice: once trimming a length the doc could not measure, once
// rewriting the doc after the spoken lines changed underneath it.
//
// So the yaml is the source and this is a view of it. Regenerate to publish;
// there is nothing to keep in sync.
package script

import (
	"fmt"
	"strings"

	"github.com/cuongtranba/narrated-video/internal/config"
	"github.com/cuongtranba/narrated-video/internal/project"
	"github.com/cuongtranba/narrated-video/internal/timing"
)

// Render returns the markdown script for one locale. An empty locale means the
// project's default.
func Render(p *project.Project, locale string) (string, error) {
	if locale == "" {
		locale = p.Config.Locales.Default
	}
	declared, ok := findLocale(p.Config, locale)
	if !ok {
		return "", fmt.Errorf("no locale %q in this project — it declares %s",
			locale, strings.Join(p.Config.LocaleCodes(), ", "))
	}

	timeline := p.Timelines[locale]
	content := p.Content[locale]

	var b strings.Builder
	fmt.Fprintf(&b, "# %s — %s (%s)\n\n", p.Config.Video.ID, declared.Label, declared.Code)
	fmt.Fprintf(&b, "%s · %d scenes · %s\n", total(timeline), len(timeline.Scenes), provenance(timeline))
	b.WriteString("\nGenerated by `nv script` from `content/" + locale + ".yaml`. Edit the yaml, not this file.\n")

	b.WriteString("\n## Narration\n")
	at := 0
	for i, scene := range timeline.Scenes {
		start := at
		at += scene.DurationInFrames - timeline.TransitionFrames
		fmt.Fprintf(&b, "\n### %d. %s — %s–%s · %s · %s\n\n",
			i+1, scene.ID,
			clock(start, timeline.FPS), clock(start+scene.DurationInFrames, timeline.FPS),
			seconds(scene.DurationInFrames, timeline.FPS), scene.Source)

		if line := strings.TrimSpace(content.Narration[scene.ID]); line != "" {
			b.WriteString(line + "\n")
			continue
		}
		b.WriteString("_(no narration — this scene is silent)_\n")
	}

	if len(content.Copy) > 0 {
		b.WriteString("\n## On screen\n\n")
		writeCopy(&b, content.Copy, 0)
	}
	return b.String(), nil
}

func writeCopy(b *strings.Builder, node map[string]any, depth int) {
	indent := strings.Repeat("  ", depth)
	for _, key := range project.SortedKeys(node) {
		switch value := node[key].(type) {
		case map[string]any:
			fmt.Fprintf(b, "%s- **%s**\n", indent, key)
			writeCopy(b, value, depth+1)
		case []any:
			fmt.Fprintf(b, "%s- **%s**\n", indent, key)
			for _, item := range value {
				fmt.Fprintf(b, "%s  - %v\n", indent, item)
			}
		default:
			fmt.Fprintf(b, "%s- **%s**: %v\n", indent, key, value)
		}
	}
}

func findLocale(cfg *config.Config, code string) (config.Locale, bool) {
	for _, l := range cfg.Locales.List {
		if l.Code == code {
			return l, true
		}
	}
	return config.Locale{}, false
}

// provenance is the one fact a reader needs before quoting a duration: whether
// it came from audio that exists or from a rate applied to a character count.
func provenance(t timing.LocaleTimeline) string {
	if t.Complete {
		return "measured from audio"
	}
	return "estimated — no audio yet"
}

func total(t timing.LocaleTimeline) string {
	return clock(t.TotalFrames, t.FPS)
}

func clock(frames, fps int) string {
	if fps <= 0 {
		return "0:00"
	}
	whole := frames / fps
	return fmt.Sprintf("%d:%02d", whole/60, whole%60)
}

func seconds(frames, fps int) string {
	if fps <= 0 {
		return "0.0s"
	}
	return fmt.Sprintf("%.1fs", float64(frames)/float64(fps))
}
